left_list = [
    "Australia",
    "Bangladesh",
    "Bermuda",
    "Bhutan",
    "Botswana",
    "Christmas Island",
    "Cocos Islands",
    "Eswatini",
    "Hong Kong",
    "India",
    "Indonesia",
    "Ireland",
    "Isle of Man",
    "Japan",
    "Jersey",
    "Kenya",
    "Lesotho",
    "Macau",
    "Malaysia",
    "Malta",
    "Namibia",
    "Nepal",
    "New Zealand",
    "Pitcairn Islands",
    "Singapore",
    "South Africa",
    "Sri Lanka",
    "Thailand",
    "Uganda",
    "United Kingdom",
    "United States Virgin Islands",
]
